package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

// This file contains resolvers for Entrepreneur type fields that require additional data loading

import (
	"context"

	"github.com/egrul-system/services/api-gateway/internal/graph/model"
	"go.uber.org/zap"
)

// Licenses is the resolver for the licenses field on Entrepreneur.
func (r *entrepreneurResolver) Licenses(ctx context.Context, obj *model.Entrepreneur) ([]*model.License, error) {
	licenses, err := r.EntrepreneurService.GetLicenses(ctx, obj.Ogrnip)
	if err != nil {
		r.Logger.Error("failed to get licenses", zap.String("ogrnip", obj.Ogrnip), zap.Error(err))
		return nil, err
	}
	return licenses, nil
}

// History is the resolver for the history field on Entrepreneur.
func (r *entrepreneurResolver) History(ctx context.Context, obj *model.Entrepreneur, limit *int, offset *int) ([]*model.HistoryRecord, error) {
	l := 50
	if limit != nil {
		l = *limit
	}
	o := 0
	if offset != nil {
		o = *offset
	}

	r.Logger.Info("History resolver called", zap.String("ogrnip", obj.Ogrnip))

	history, err := r.EntrepreneurService.GetHistory(ctx, obj.Ogrnip, l, o)
	if err != nil {
		r.Logger.Error("failed to get history", zap.String("ogrnip", obj.Ogrnip), zap.Error(err))
		return nil, err
	}
	
	r.Logger.Info("History loaded", zap.String("ogrnip", obj.Ogrnip), zap.Int("count", len(history)))
	return history, nil
}

// HistoryCount is the resolver for the historyCount field on Entrepreneur.
func (r *entrepreneurResolver) HistoryCount(ctx context.Context, obj *model.Entrepreneur) (int, error) {
	r.Logger.Info("HistoryCount resolver called", zap.String("ogrnip", obj.Ogrnip))
	
	count, err := r.EntrepreneurService.GetHistoryCount(ctx, obj.Ogrnip)
	if err != nil {
		r.Logger.Error("failed to get history count", zap.String("ogrnip", obj.Ogrnip), zap.Error(err))
		return 0, err
	}
	r.Logger.Info("HistoryCount loaded", zap.String("ogrnip", obj.Ogrnip), zap.Int("count", count))
	return count, nil
}

// Entrepreneur returns EntrepreneurResolver implementation.
func (r *Resolver) Entrepreneur() EntrepreneurResolver { return &entrepreneurResolver{r} }

type entrepreneurResolver struct{ *Resolver }

