// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

// Ответ при успешной аутентификации
type AuthResponse struct {
	User      *User     `json:"user"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expiresAt"`
}

// Сортировка предпринимателей
type EntrepreneurSort struct {
	Field EntrepreneurSortField `json:"field"`
	Order *SortOrder            `json:"order,omitempty"`
}

// Входные данные для входа
type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

// Входные данные для регистрации
type RegisterInput struct {
	Email     string `json:"email"`
	Password  string `json:"password"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

// Пользователь системы
type User struct {
	ID            string     `json:"id"`
	Email         string     `json:"email"`
	FirstName     string     `json:"firstName"`
	LastName      string     `json:"lastName"`
	IsActive      bool       `json:"isActive"`
	EmailVerified bool       `json:"emailVerified"`
	CreatedAt     time.Time  `json:"createdAt"`
	UpdatedAt     time.Time  `json:"updatedAt"`
	LastLoginAt   *time.Time `json:"lastLoginAt,omitempty"`
}

// Точка временного ряда (регистрации/ликвидации)
type TimeSeriesPoint struct {
	Month              string `json:"month"`
	RegistrationsCount int    `json:"registrationsCount"`
	TerminationsCount  int    `json:"terminationsCount"`
	NetGrowth          int    `json:"netGrowth"`
}

// Расширенная статистика для дашборда
type DashboardStatistics struct {
}

// Поле для сортировки предпринимателей
type EntrepreneurSortField string

const (
	EntrepreneurSortFieldOgrnip           EntrepreneurSortField = "OGRNIP"
	EntrepreneurSortFieldInn              EntrepreneurSortField = "INN"
	EntrepreneurSortFieldFullName         EntrepreneurSortField = "FULL_NAME"
	EntrepreneurSortFieldRegistrationDate EntrepreneurSortField = "REGISTRATION_DATE"
	EntrepreneurSortFieldUpdatedAt        EntrepreneurSortField = "UPDATED_AT"
)

var AllEntrepreneurSortField = []EntrepreneurSortField{
	EntrepreneurSortFieldOgrnip,
	EntrepreneurSortFieldInn,
	EntrepreneurSortFieldFullName,
	EntrepreneurSortFieldRegistrationDate,
	EntrepreneurSortFieldUpdatedAt,
}

func (e EntrepreneurSortField) IsValid() bool {
	switch e {
	case EntrepreneurSortFieldOgrnip, EntrepreneurSortFieldInn, EntrepreneurSortFieldFullName, EntrepreneurSortFieldRegistrationDate, EntrepreneurSortFieldUpdatedAt:
		return true
	}
	return false
}

func (e EntrepreneurSortField) String() string {
	return string(e)
}

func (e *EntrepreneurSortField) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EntrepreneurSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EntrepreneurSortField", str)
	}
	return nil
}

func (e EntrepreneurSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
